apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stratex
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/egangithub1502/kilo-code.git  # Replace with your Git repository URL
    path: frontend/stratex
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: profit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
