apiVersion: v1
kind: Service
metadata:
  name: stratex-preview-svc
  namespace: profit
  labels:
    app: stratex
    enabled: "true"
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: stratex
    enabled: "true"
  type: ClusterIP

