apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: stratex
  namespace: profit
  labels:
    app: stratex
    enabled: "true"
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: stratex-svc
      previewService: stratex-preview-svc
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: stratex
  template:
    metadata:
      labels:
        app: stratex
        enabled: "true"
    spec:
      containers:
        - name: stratex
          image: us-central1-docker.pkg.dev/stm-01/my-app-repo/html-nginx-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      nodeSelector:
        cloud.google.com/gke-nodepool: jegan-test-cluster-pool

